### ISSUE TITLE
Can't create bot instance

### ISSUE THREAD

**Issue by HarHarLinks** [MoralCode/maubot-events#3]
I tried to install this bot in the way that maubot plugins are usually installed. That is:
1. since you don't provide the plugin prebuilt, i [build and upload](https://docs.mau.fi/maubot/usage/cli/build.html) it `mbc build maubot-events -u` based on the v0.2.0 tag
2. in the maubot web ui, create a new instance with some existing client and the org.fedoraproject.maubot.events plugin
3. it fails:
```
[00:46:57](file:///opt/maubot/maubot/loader/zip.py:203)	ERROR	maubot.loader.zip	Failed to load org.fedoraproject.maubot.events v0.2.0
[00:46:57](file:///opt/maubot/maubot/loader/zip.py:203)	ERROR	maubot.loader.zip	Traceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 216, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 280, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/org.fedoraproject.maubot.events-v0.2.0.mbp/event_helper/__init__.py", line 14, in <module>
    import validators
ModuleNotFoundError: No module named 'validators'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 201, in load
    return self._load(reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/loader/zip.py", line 220, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module event_helper
[00:46:57](file:///opt/maubot/maubot/management/api/middleware.py:68)	ERROR	maubot.server	Error in handler
[00:46:57](file:///opt/maubot/maubot/management/api/middleware.py:68)	ERROR	maubot.server	Traceback (most recent call last):
  File "/opt/maubot/maubot/loader/zip.py", line 216, in _load
    importer.load_module(module)
  File "/opt/maubot/maubot/lib/zipimport.py", line 280, in load_module
    exec(code, mod.__dict__)
  File "/data/plugins/org.fedoraproject.maubot.events-v0.2.0.mbp/event_helper/__init__.py", line 14, in <module>
    import validators
ModuleNotFoundError: No module named 'validators'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/maubot/management/api/middleware.py", line 49, in error
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/management/api/instance.py", line 83, in update_instance
    return await _create_instance(instance_id, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/management/api/instance.py", line 59, in _create_instance
    await instance.start()
  File "/opt/maubot/maubot/instance.py", line 362, in start
    cls = await self.loader.load()
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/loader/zip.py", line 201, in load
    return self._load(reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/maubot/maubot/loader/zip.py", line 220, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module event_helper
```

**Comment by MoralCode** [comment]
Honestly ive sorta been working a little backwards and starting from the development environment at https://github.com/fedora-infra/matrix-bots.

That said, despite this being my first time using maubot, I do use a very similar `mbc build`step within the dev environment.

Based on the error above it seems like the environment you are trying to build the bot in does not have all the dependencies installed. If you run `pip install -r requirements.txt` and then retry your build command, does it work?

**Comment by HarHarLinks** [comment]
Here is the maubot development manual: https://docs.mau.fi/maubot/dev/getting-started.html
I tried adding validators to the maubot.yaml dependencies, but that does not work either. I believe that building the plugin needs to build any dependencies that are not part of the default maubot distribution into the plugin package.

Also, I am running maubot itself in a container (https://docs.mau.fi/maubot/usage/setup/docker.html). No easy installing random python packages.

**Comment by MoralCode** [comment]
thankfully i wasnt using the `validators` package for much anyway (other than domain name validation for matrix IDs) so i replaced this with essentially copy pasting the regex from the source code of that package

Can you check out the `validators-fix` branch to see if that helps fix things?

**Comment by HarHarLinks** [comment]
Now I get the same error for the next library. I think we need to solve how to properly package the plugin.

**Comment by MoralCode** [comment]
i also looked at the [docs](https://docs.mau.fi/maubot/dev/reference/plugin-metadata.html?highlight=dependencies#plugin-metadata) for the dependencies config entry and it said this (emphasis mine)

> dependencies - A list of Python modules and their version ranges that the plugin requires. **This is currently not used, but in the future maubot will offer to automatically install dependencies when uploading a plugin.**

so i think i just need to do a better job of documenting the dependency requirements of this bot, at least until maubot supports this config item (right now it just seems like it is a non-functional equivalent to `requirements.txt` embedded into `maubot.yaml` for possible future use.

Would it help if i created a docker container that was based on the maubot official one you said you were using, but with the correct python dependencies installed for this plugin?

**Comment by HarHarLinks** [comment]
Looking at https://plugins.mau.bot I see some plugins that _appear_ to manage dealing with dependencies. On the other hand the install instructions for https://github.com/SAPUCC/inviterbot?tab=readme-ov-file#installation support what you have been saying, that is the need to install the deps in the maubot server('s container). I did what the latter recommends and the plugin now loads.

**Comment by MoralCode** [comment]
sounds good!

I'll update this issue to become an "FYI, use a proper maubot dependency management tool when one becomes available in maubot" issue. If theres an upstream issue in maubot to add this feature, I'd love to link it!

**Comment by HarHarLinks** [comment]
https://github.com/maubot/maubot/issues/10

**Comment by HarHarLinks** [comment]
For now, what could be done is to explain the situation in the installation instructions. It could go so far as to even provide a prebuilt container via ghcr.io that comes with the required dependencies. I've set up the same in a private repo for myself for now.
